### ISSUE TITLE
Generated INI entry for LayeredFS + Sys-Netcheat crashes at bootup

### ISSUE THREAD

**Issue by Targren** [noahc3/SDSetup#16]
Installing Atmosphere with Sigpatches and Sys-Netcheat options generates this entry in /bootloader/sys-netcheat.ini 

`[LayeredFS + sys-netcheat]
kip1=modules/newfirm/loader.kip
kip1=modules/newfirm/sm.kip
kip1=modules/newfirm/fs_mitm.kip
kip1=modules/newfirm/pm.kip
kip1=modules/sys-netcheat.kip
atmosphere=1
kip1patch=nosigchk
debugmode=1
fullsvcperm=1`

When trying to boot from this entry in Hekate, startup gets to the "Switch" logo, then hangs. 

Tested it as of 2018-09-29 at 1130h EDT.

Not sure if its an incompatibility between the modules, or a problem in the way the ini file is generated. 

Edit: Sorry, should probably have included that I'm on 5.1.0

**Comment by tumGER** [comment]
Fixed on SDFiles side (v9.0.4 / https://github.com/tumGER/SDFilesSwitch/commit/17f989adf12d4644f92d5f03a30e32d4d23a6a2c)

**Comment by noahc3** [comment]
Yea I'm going to mass update all the sdfiles modules cause everything currently is a mishmash of v8.1-9.0.4 and I've probably missed some updates along the way.

**Comment by Targren** [comment]
@tumger I manually added the two secmon lines into the ini file, but no dice. It still hangs on the "Nintendo Switch" logo.

**Comment by noahc3** [comment]
@Targren CFW + sys-netcheat now works, are you talking about something else?

**Comment by Targren** [comment]
[LayeredFS + sys-netcheat]

CFW + sys-netcheat doesn't include fs_mitm.kip

**Comment by noahc3** [comment]
@tumGER LayeredFS + sys-netcheat does not work with 9.0.4 files from the release either

**Comment by tumGER** [comment]
https://github.com/jakibaki/sys-netcheat/releases

**Comment by tumGER** [comment]
Fixed for real now

**Comment by tumGER** [comment]
(oh wait, this still needs to be added to the sdsetup)
